return PlaceObj('ModDef', {
	'title', "Revised Tactical Gear II",
	'description', "This is a reworked and enhanced rerelease of [b]Ablomis'[/b] Revised Tactical Gear mod with a new Inventory layout which was designed by [b]Lucjan[/b] who is also helping me with improving this mod.\n\nThis mod adds more inventory slots to the game (Backpack, LBE, Leg items, Face items, NVG slot) and introduces weight.\n\n[b]New Mod Options[/b]\nTo activate the options you have to restart Jagged Alliance 3\n[list]\n[*]Option to put bullets in mag pouches\n[*]Option to make items like meds and parts lighter to be able to carry everything around with your squad\n[/list]\n\n[b]New Shortcuts for Sector Inventory View[/b]\n[list]\n[*]Ctrl-Shift-U: Unload all weapons (and Mags)\n[*]Ctrl-Shift-D: Move all inventory items of the selected merc to the sector inventory\n[*]Ctrl-Shift-E: Move all items from equip-slots of the selected merc to the sector inventory\n[*]Ctrl-Shift-B: Move all items from squad bag to the sector inventory\n[*]Ctrl-Shift-C: Remove all items from LBEs, backpacks and holsters in sector inventory\n[*]Ctrl-Shift-S: Sort all items in sector inventory\n[*]Ctrl-Shift-M: Merge items in sector inventory\n[/list]\n\nI also added a shortcut which will activate and deactivate rollovers in inventory view (the toggle does only work in satellite view at the moment but rollovers are also deactivated in exploration): Ctrl-Shift-N\n\n[b]Important[/b]\n[list]\n[*]Restart the game after activating the mod\n[*]It is not 100% save-game compatible and it may happen, that you will loose some items. I recommend using Ctrl-Shift-D in sector inventory view to drop all items.\n[*]Mod compatibility is very low\n[*]If you are a mod creator and want to increase compatibility, please contact me\n[*]Revised Mags II Mod is a dependency of this mod. \n[*]There was decent amount of playtesting but there can still be bugs.\n[*]If you find bugs, please send me your bug reports.\n[/list]\n\n[b]Copyright[/b]\nLBE and some holster images are from AdobeStock\nBackpacks, the goggle and the rest of the holsters are created with ChatGPT and Bing image creation",
	'image', "Mod/ii6mKUf/Images/JA3Revised-title.png",
	'last_changes', "Reevaluation of all weights\nAdded mod option to allow bullets inside magazine pouches\nAdded mod option to make some items lighter\nAdded missing slot definitions for some items\nReadded decimal in Inventory screen to weights\nFixed problem when items were granted by NPCs",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "URkxyfE",
			'title', "Revised Mags",
		}),
	},
	'id', "ii6mKUf",
	'author', "permanent666",
	'version_minor', 16,
	'version', 487,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/CODE_CustomSettingSort.lua",
		"Code/CODE_WeightCalc.lua",
		"Code/CODE_Inventory.lua",
		"Code/CODE_LBEBuilder.lua",
		"Code/CODE_LootDrop.lua",
		"InventoryItem/Holster_Drop_Leg_Bag.lua",
		"InventoryItem/Holster_Extended.lua",
		"InventoryItem/Holster_Basic.lua",
		"InventoryItem/LBE_Heavy_Duty_Vest.lua",
		"InventoryItem/LBE_Cheap_Vest.lua",
		"InventoryItem/LBE_Combat_Vest.lua",
		"InventoryItem/LBE_Modern_Army_Rig.lua",
		"InventoryItem/LBE_Basic_Army_Rig.lua",
		"InventoryItem/LBE_Basic_Rig.lua",
		"InventoryItem/LBE_SWAT_Vest.lua",
		"InventoryItem/Backpack_Blackhawk.lua",
		"InventoryItem/Backpack_Modern.lua",
		"InventoryItem/Backpack_Combat.lua",
		"InventoryItem/Backpack_Mule.lua",
		"InventoryItem/Backpack_Retro.lua",
		"InventoryItem/Backpack_Retro_Large.lua",
		"InventoryItem/FaceItem_Combat_Goggles.lua",
		"Code/X_XRollover.lua",
		"Code/X_Inventory_full.lua",
		"Code/X_SquadsAndMercs.lua",
		"Code/X_InventoryContextMenu.lua",
		"Code/X_Inventory.lua",
		"Code/X_Utils.lua",
		"Code/OR_Unit.lua",
		"Code/OR_Mercenary.lua",
		"Code/OR_UnitProperties.lua",
		"Code/OR_Inventory.lua",
		"Code/OR_InventoryUI.lua",
		"Code/OR_MoveItem.lua",
		"Code/OR_CombatActions.lua",
		"Code/SETUP_SlotConfig.lua",
		"Code/SETUP_Config.lua",
		"Code/SETUP_LBEItemDef.lua",
		"Code/SETUP_SlotDefs.lua",
		"Code/SETUP_ModOptions.lua",
		"Code/SETUP_Weight.lua",
		"CharacterEffect/Overweight.lua",
	},
	'default_options', {
		RevisedLBEDropChance = "5",
		RevisedLighterItems = false,
		RevisedPouchesHoldBullets = false,
		RevisedSquadBagHasWeight = true,
	},
	'has_data', true,
	'saved', 1713743014,
	'code_hash', -9122465868298641459,
	'screenshot1', "Mod/ii6mKUf/Images/Screenshot 2024-04-07 020350 2.png",
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Holster_Drop_Leg_Bag",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Holster_Extended",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Holster_Basic",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Heavy_Duty_Vest",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Cheap_Vest",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Combat_Vest",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Modern_Army_Rig",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Basic_Army_Rig",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_Basic_Rig",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "LBE_SWAT_Vest",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Blackhawk",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Modern",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Combat",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Mule",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Retro",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "Backpack_Retro_Large",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FaceItem_Combat_Goggles",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "TextStyle",
			'Id', "REVLBELegendText",
			'ClassDisplayName', "Text style",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Overweight",
			'ClassDisplayName', "Character effect",
		}),
	},
	'steam_id', "3178380968",
	'TagWeapons&Items', true,
})