return PlaceObj('ModDef', {
	'title', "Revised LBE",
	'id', "ii6mKUf",
	'author', "Ablomis",
	'version', 155,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/BackpackItems.lua",
		"Code/Config.lua",
		"Code/Inventory.lua",
		"Code/LBEBuilder.lua",
		"Code/LBEItemDef.lua",
		"Code/LBEItems.lua",
		"Code/LootDrop.lua",
		"Code/UnitInventory.lua",
		"Code/XTemplateInventory.lua",
	},
	'saved', 1693850367,
	'code_hash', 6884496604557989368,
})